version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint test
          command: npm run eslint
      - run:
          name: Run tests
          command: npm run test:prod
  deploy:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build docs
          command: npm run generate-docs
      - run:
          name: Semantic Release
          command: npm run semantic-release
      - add_ssh_keys:
          fingerprints:
            - '1a:33:f0:44:2d:d5:e4:ca:74:2b:89:1c:eb:6e:0c:31'
      - run:
          name: Deploy docs
          command: npm run gh-pages

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

branches:
  ignore:
    - gh-pages
